// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2VWimE29GHchRWB2RNdcSpK_KEZhfABw',
    appId: '1:68585758841:web:8e096440b38811129c34a8',
    messagingSenderId: '68585758841',
    projectId: 'airhouse-6eacf',
    authDomain: 'airhouse-6eacf.firebaseapp.com',
    storageBucket: 'airhouse-6eacf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpxSsw3yHzaNQ48alqE7MbGWcG5KyqOPw',
    appId: '1:68585758841:android:c4f48c8e9fa3a5229c34a8',
    messagingSenderId: '68585758841',
    projectId: 'airhouse-6eacf',
    storageBucket: 'airhouse-6eacf.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2VWimE29GHchRWB2RNdcSpK_KEZhfABw',
    appId: '1:68585758841:web:dc4a524df610c8579c34a8',
    messagingSenderId: '68585758841',
    projectId: 'airhouse-6eacf',
    authDomain: 'airhouse-6eacf.firebaseapp.com',
    storageBucket: 'airhouse-6eacf.appspot.com',
  );
}
